### ISSUE TITLE
failed in pypy v5.8

### ISSUE THREAD

**Issue by Infixz** [MagicStack/httptools#28]
```
Python 2.7.13 (5.8.0+dfsg-2~ppa2~ubuntu14.04, Jun 17 2017, 18:51:40)
[PyPy 5.8.0 with GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import httptools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chengs/playground/pypy5.8env/.env/site-packages/httptools/__init__.py", line 1, in <module>
    from .parser import *
TypeError: 'Item in ``fromlist'' must be str, not unicode
```

**Comment by elprans** [comment]
httptools does requires Python 3.5 at the minimum, and PyPy3 is unlikely to work well given that httptools is a binary extension.
